// Release notes shown on the Help page (/help), newest date first.
// One entry per commit. type: 'new' | 'improved' | 'fixed' | 'removed'
// When you push a new change, add a line at the top of the matching date (or a new date block).

module.exports = [
  {
    date: '2026-10-03',
    items: [
      { commit: '', type: 'new', title: 'Move data to another server',
        details: ['Backup & Restore → Export Data + Files: one download with all data plus uploaded photos, receipts and documents.',
                  'Upload Backup on the new server, click Restore, then restart the server to bring everything across.'] },
    ],
  },
  {
    date: '2026-09-30',
    items: [
      { commit: '', type: 'improved', title: 'New machine quotation price layout',
        details: ['Transit Insurance removed.',
                  'Roundoff now comes right after TCS and gives the Ex-Showroom Price (replaces "Sub Total").',
                  'After Ex-Showroom: Insurance with IMT-23 (₹ amount), TRC / LTT (6% of Ex-Showroom by default, editable), Handling Charges (₹20,000 by default) and Transport, then the Grand Total.'] },
      { commit: '', type: 'new', title: 'Spare Part Orders',
        details: ['Spares → Part Orders: look up a sold machine, add parts from the Parts Master, and place an order.',
                  'Admin confirms or deletes orders; the person who placed an order can cancel it while pending.'] },
      { commit: '', type: 'new', title: 'Backup & Restore (admin)',
        details: ['Operations → System → Backup & Restore: one-click database and code backups, with download.',
                  'Restoring a backup saves the current data first and applies on the next server restart.'] },
    ],
  },
  {
    date: '2026-09-23',
    items: [
      { commit: '', type: 'improved', title: 'Sidebar redesigned into 5 sections',
        details: ['Sales, Operations, Spares, Service and Human Resources, each collapsible.',
                  'You only see the sections and links your login role can use.',
                  'The section for the current page opens automatically; your open/closed choices are remembered.',
                  'My Route and Update Prices now have their own menu links.'] },
      { commit: 'c8fad69', type: 'new', title: 'Help & Updates page',
        details: ['Tap the (?) icon to see every app improvement, date by date.'] },
    ],
  },
  {
    date: '2026-08-31',
    items: [
      { commit: '82e75f7', type: 'improved', title: 'Mobile top bar title goes home',
        details: ['Tapping "SUPER ALLIED" in the mobile top bar now opens the Dashboard from any page.'] },
      { commit: 'cb25ddd', type: 'fixed', title: 'Travel expense rates corrected on live server',
        details: ['Own Two Wheeler ₹3/km and Own Four Wheeler ₹5/km now apply on production.',
                  'Travel type is now exactly three options: Own Two Wheeler, Own Four Wheeler, Company Vehicle ("Other" removed).'] },
      { commit: 'c02e771', type: 'fixed', title: 'My Route page no longer crashes',
        details: ['Map always loads, centred on your live GPS location, then fits today\'s check-in, visits and check-out.',
                  'New "Today\'s Tasks" checklist above the map.'] },
      { commit: 'd1f63c9', type: 'improved', title: 'Simpler travel claims, safer user removal, private customer lists',
        details: ['Travel claims capture distance only for now; vehicle number comes from the employee profile.',
                  'Users are now deactivated/reactivated instead of hard-deleted (no more delete errors).',
                  'Sales role no longer has Machine Quotations and Form 22 access; server-side checks added.',
                  'Non-admin users see only customers they created.'] },
      { commit: '175970f', type: 'new', title: 'Motor Vehicle Travel Expense module',
        details: ['Draft → submit → approve/reject claim workflow with receipt uploads.',
                  'Admin-editable per-vehicle reimbursement rates.',
                  'Fixed Site Punch-In photo not being captured; added Contact Person, Purpose and a Visit ID confirmation.',
                  'Deactivated HR accounts can no longer log in; employee list gets Role/Status filters.',
                  'Audit log now records user and expense actions.'] },
      { commit: 'f1b4166', type: 'fixed', title: 'Sales Reports page works again',
        details: ['Salesperson summary report restored with spare + machine stats and monthly trend.'] },
      { commit: '86c36d3', type: 'new', title: 'Form 22 module',
        details: ['Generate Form 22 with PDF download from Sales → Form 22.'] },
      { commit: 'b9d83c3', type: 'improved', title: 'Standard 14-point Terms & Conditions on spare quotations',
        details: ['Covers validity, taxes, payment, delivery, warranty, jurisdiction, force majeure and acceptance.'] },
    ],
  },
  {
    date: '2026-08-27',
    items: [
      { commit: 'e71da03', type: 'fixed', title: 'Salesperson removal now deactivates instead of deleting',
        details: ['Old quotations keep their salesperson; inactive salespersons can be reactivated.'] },
    ],
  },
  {
    date: '2026-08-17',
    items: [
      { commit: 'ee338bc', type: 'new', title: 'Full salesperson management',
        details: ['Add/edit salespersons with phone, email, territory and monthly target.',
                  'Set a default salesperson; name and phone shown on machine quotation view and PDF.'] },
      { commit: '222a7d2', type: 'removed', title: 'Stamp removed from machine quotations',
        details: ['Original price breakdown layout restored.'] },
    ],
  },
  {
    date: '2026-08-01',
    items: [
      { commit: '8464a7d', type: 'new', title: 'Enquiry CRM pipeline (replaces Lead Management)',
        details: ['Each customer is one Enquiry with a full timeline of remarks, follow-ups, visits, quotations and sale.',
                  '4 stages: Phone Follow-up → Sales Visit → Enquiry Generated → Sales Closed.',
                  'Kanban board, dashboard, list, quotation PDF, click-to-call/WhatsApp/maps, GPS + photo visits, voice-to-text remarks, duplicate-phone check, Excel export.',
                  'All old leads migrated automatically.'] },
      { commit: 'adb17ad', type: 'fixed', title: 'Stamp shows reliably in quotation PDFs',
        details: ['Stamp is now built into the app instead of loading from Google Drive.'] },
    ],
  },
  {
    date: '2026-07-30',
    items: [
      { commit: 'aee80c3', type: 'new', title: 'Super Allied Meerut stamp on quotations',
        details: ['Stamp added at bottom-right of quotation view and PDF.'] },
    ],
  },
  {
    date: '2026-07-01',
    items: [
      { commit: '1f34671', type: 'removed', title: 'Solar Quotation module withdrawn',
        details: ['The solar module added earlier the same day was rolled back.'] },
      { commit: '6385aff', type: 'new', title: 'Solar Quotation module (trial)',
        details: ['Rooftop solar quotations with separate customers and SOL-FY numbering. Rolled back the same day.'] },
    ],
  },
  {
    date: '2026-06-29',
    items: [
      { commit: '8fb67ec', type: 'fixed', title: 'App start-up fix',
        details: ['Removed a reference to a backup feature that did not exist yet.'] },
    ],
  },
  {
    date: '2026-06-27',
    items: [
      { commit: '8cb3930', type: 'improved', title: 'Deleting a user can hand their work to admin',
        details: ['Confirmation box with a "reassign to admin" option for quotations, leads, sold machines and stock updates.'] },
    ],
  },
  {
    date: '2026-06-25',
    items: [
      { commit: '9e0f893', type: 'fixed', title: 'Spare quotation part picker no longer breaks after 19 items',
        details: ['Part names with quotes or special characters no longer break the list.'] },
      { commit: '6bbbc72', type: 'fixed', title: 'Stock module shows correct part numbers and descriptions', details: [] },
      { commit: '8d9b90c', type: 'new', title: 'Stock Availability module',
        details: ['Colour-coded stock list with filters, edit, Excel import/export and template download.',
                  'Live stock badge next to quantity in spare quotation form.',
                  'Stock is never shown on customer PDFs.'] },
    ],
  },
  {
    date: '2026-06-20',
    items: [
      { commit: '239dfd3', type: 'fixed', title: 'User deletion errors fixed',
        details: ['Quotation history is kept when a user is deleted.'] },
    ],
  },
  {
    date: '2026-06-19',
    items: [
      { commit: '23bae88', type: 'new', title: 'Universal search bar',
        details: ['Search machines, customers, quotations, spare parts, sold machines and employees from the sidebar.',
                  'Roundoff can now be as small as ₹1.'] },
      { commit: 'c53a0b6', type: 'improved', title: 'Simple selling-price update screen',
        details: ['Machine Master → Update Prices: edit selling prices in one table, auto-save on Enter/Tab.'] },
      { commit: '55d6118', type: 'new', title: 'Purchase price table (replaced next commit)',
        details: ['Purchase price with profit margin view; later replaced by the simpler price update screen.'] },
    ],
  },
  {
    date: '2026-06-17',
    items: [
      { commit: '0e27dc5', type: 'improved', title: 'Role-based access for Sales and Office',
        details: ['Sales: machine quotations, leads, visits, attendance, expenses, customers.',
                  'Office: everything Sales has plus spares. Manager: Sales + Spares + HR admin.',
                  'Users page shows a role access summary.'] },
      { commit: '9504b59', type: 'fixed', title: 'Salesperson profile page error fixed', details: [] },
      { commit: '3726a6b', type: 'fixed', title: 'Salesperson totals use the correct price field', details: [] },
      { commit: 'e392ada', type: 'new', title: 'Column mapping for Excel import',
        details: ['Sold machines and spare parts import: upload → map columns (auto-detected) → import, with sample values.'] },
      { commit: 'b83341e', type: 'fixed', title: 'Spare quotation fixes and approval flow',
        details: ['GST auto-calculated and checked; standard roundoff.',
                  'PDF gets a separate Part No. column; payment details moved to the end.',
                  'Submit for Approval, admin approve/reject with notes, WhatsApp share.'] },
      { commit: '8e84756', type: 'improved', title: 'Salesperson dropdowns, new sidebar, GST-invoice-style spare PDF',
        details: ['Sidebar reorganised into Sales, Spares and HR sections.',
                  'Default quotation validity changed from 30 to 7 days.',
                  'New company fields: email, UDYAM, sales/service phones, state.'] },
      { commit: '88f5608', type: 'improved', title: 'Spare quotation PDF and form redesign',
        details: ['Editable quotation date; optional discount column; NDP removed from customer PDF.'] },
      { commit: 'a67738d', type: 'improved', title: 'Sold machine import needs only machine number', details: [] },
      { commit: '94cbfcc', type: 'fixed', title: 'Large Excel imports work (10,000 rows / 1 MB)',
        details: ['Progress feedback during upload; imports about 10x faster.'] },
      { commit: '171cd01', type: 'new', title: 'Upward roundoff on quotations',
        details: ['Configurable in Settings, e.g. ₹45,230 → ₹45,500 with roundoff 500.'] },
      { commit: '3718665', type: 'fixed', title: 'Selected tyre option now saves', details: [] },
      { commit: '2f5cf30', type: 'new', title: 'Tyre option on machine quotations',
        details: ['Choose IT Tyre 16.09x28 (default) or HD Tyre 14.00x25; shown on view and PDF.'] },
    ],
  },
  {
    date: '2026-06-12',
    items: [
      { commit: '35dd76b', type: 'new', title: 'Spare Parts Quotation system',
        details: ['Sold Machines register with search and Excel import.',
                  'Parts Master with 10,735 Bull parts.',
                  '3-step spare quotation with CGST/SGST or IGST, clone, status, WhatsApp share, PDF with QR.',
                  'Parts reports and dashboard cards.'] },
    ],
  },
  {
    date: '2026-06-10',
    items: [
      { commit: 'e052b72', type: 'fixed', title: 'Tabs on lead pages work', details: [] },
      { commit: '6644d58', type: 'new', title: 'Lead Management (5-stage pipeline)',
        details: ['Docs/CIBIL → FI → Loan → DO → Post-delivery, with Kanban board and analytics.'] },
      { commit: '061f958', type: 'improved', title: 'Quotations locked to MRP; RTO default 6%',
        details: ['Sales staff see a locked MRP; admin can still override.',
                  'RTO auto-calculated at 6%; Price Lock toggle in Settings.'] },
      { commit: '03e1ac3', type: 'new', title: 'Machine Management console and default salesperson',
        details: ['Add/edit machines and their specs; specs shown on quotations and PDFs.'] },
      { commit: '9de3efa', type: 'improved', title: 'Bull machine MRPs updated (May 2026 price list)',
        details: ['14 models, from ₹27,90,000 (Skid Steer) to ₹44,98,000 (Supersmart AC 4WD).'] },
      { commit: 'e9e299b', type: 'improved', title: 'Journey tracking and photo-first field visits',
        details: ['Odometer reading and vehicle photo at check-in/out; total KM calculated.',
                  'Field visits require a photo and customer name.'] },
    ],
  },
  {
    date: '2026-05-30',
    items: [
      { commit: '55b8b7a', type: 'improved', title: 'Permissions, employee dashboard, route map',
        details: ['Configurable per-role permissions; new roles Sales, Service, HR, Office.',
                  'Tile-style employee dashboard, field visit logging, My Route map, My Profile with photo.',
                  'ID card and attendance photo fixes.'] },
      { commit: '36fb170', type: 'new', title: 'HR & Field Force module',
        details: ['Selfie + GPS attendance, digital ID card, leave management, salary slips, notifications, HR dashboard.'] },
    ],
  },
  {
    date: '2026-05-29',
    items: [
      { commit: '4e59fc7', type: 'fixed', title: 'TRC included in grand total; staff see only their own quotations', details: [] },
      { commit: '876f34c', type: 'new', title: 'Mobile layout, Sales Staff role, user management', details: [] },
      { commit: 'efa6c98', type: 'new', title: 'First release of the Super Allied quotation app',
        details: ['Machine quotations with PDF (Bull logo + bank QR), profit calculator.'] },
    ],
  },
];
